//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knigi.BD
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media.Imaging;

    public partial class book
    {
        public int Номер { get; set; }
        public Nullable<int> НомерВида { get; set; }
        public Nullable<int> НомерАвтор { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
        public Nullable<double> Цена { get; set; }
        public string Изображение { get; set; }
        public BitmapImage PhotoFullPath => new BitmapImage(new Uri($"{Environment.CurrentDirectory.Substring(0, Environment.CurrentDirectory.Length - 10)}/Resource/{Изображение}"));
       // public string PhotoFullPath => $"/Resource/{Изображение}";

        public virtual autor autor { get; set; }
        public virtual view view { get; set; }
    }
}
